// Centralized stock images catalog used by both authoring and student runtime.
// IMPORTANT: React Native requires static require() calls; this file enumerates
// all bundled stock images so they can be registered with the local image
// resolver and referenced by filename for fast, offline loading.

export const stockImages: Record<string, Array<{ name: string; uri: any }>> = {
  '3D Alphabet': [
    { name: '3D A', uri: require('../assets/images/Stock-Images/3D Alphabet/A1.png') },
    { name: '3D B', uri: require('../assets/images/Stock-Images/3D Alphabet/B1.png') },
    { name: '3D C', uri: require('../assets/images/Stock-Images/3D Alphabet/C1.png') },
    { name: '3D D', uri: require('../assets/images/Stock-Images/3D Alphabet/D1.png') },
    { name: '3D E', uri: require('../assets/images/Stock-Images/3D Alphabet/E1.png') },
    { name: '3D F', uri: require('../assets/images/Stock-Images/3D Alphabet/F1.png') },
    { name: '3D G', uri: require('../assets/images/Stock-Images/3D Alphabet/G1.png') },
    { name: '3D H', uri: require('../assets/images/Stock-Images/3D Alphabet/H1.png') },
    { name: '3D I', uri: require('../assets/images/Stock-Images/3D Alphabet/I1.png') },
    { name: '3D J', uri: require('../assets/images/Stock-Images/3D Alphabet/J1.png') },
    { name: '3D K', uri: require('../assets/images/Stock-Images/3D Alphabet/K1.png') },
    { name: '3D L', uri: require('../assets/images/Stock-Images/3D Alphabet/L1.png') },
    { name: '3D M', uri: require('../assets/images/Stock-Images/3D Alphabet/M1.png') },
    { name: '3D N', uri: require('../assets/images/Stock-Images/3D Alphabet/N1.png') },
    { name: '3D O', uri: require('../assets/images/Stock-Images/3D Alphabet/O1.png') },
    { name: '3D P', uri: require('../assets/images/Stock-Images/3D Alphabet/P1.png') },
    { name: '3D Q', uri: require('../assets/images/Stock-Images/3D Alphabet/Q1.png') },
    { name: '3D R', uri: require('../assets/images/Stock-Images/3D Alphabet/R1.png') },
    { name: '3D S', uri: require('../assets/images/Stock-Images/3D Alphabet/S1.png') },
    { name: '3D T', uri: require('../assets/images/Stock-Images/3D Alphabet/T1.png') },
    { name: '3D U', uri: require('../assets/images/Stock-Images/3D Alphabet/U1.png') },
    { name: '3D V', uri: require('../assets/images/Stock-Images/3D Alphabet/V1.png') },
    { name: '3D W', uri: require('../assets/images/Stock-Images/3D Alphabet/W1.png') },
    { name: '3D X', uri: require('../assets/images/Stock-Images/3D Alphabet/X1.png') },
    { name: '3D Y', uri: require('../assets/images/Stock-Images/3D Alphabet/Y1.png') },
    { name: '3D Z', uri: require('../assets/images/Stock-Images/3D Alphabet/Z1.png') },
  ],
  Alphabet: [
    { name: 'A', uri: require('../assets/images/Stock-Images/Alphabet/A.png') },
    { name: 'B', uri: require('../assets/images/Stock-Images/Alphabet/B.png') },
    { name: 'C', uri: require('../assets/images/Stock-Images/Alphabet/C.png') },
    { name: 'D', uri: require('../assets/images/Stock-Images/Alphabet/D.png') },
    { name: 'E', uri: require('../assets/images/Stock-Images/Alphabet/E.png') },
    { name: 'F', uri: require('../assets/images/Stock-Images/Alphabet/F.png') },
    { name: 'G', uri: require('../assets/images/Stock-Images/Alphabet/G.png') },
    { name: 'H', uri: require('../assets/images/Stock-Images/Alphabet/H.png') },
    { name: 'I', uri: require('../assets/images/Stock-Images/Alphabet/I.png') },
    { name: 'J', uri: require('../assets/images/Stock-Images/Alphabet/J.png') },
    { name: 'K', uri: require('../assets/images/Stock-Images/Alphabet/K.png') },
    { name: 'L', uri: require('../assets/images/Stock-Images/Alphabet/L.png') },
    { name: 'M', uri: require('../assets/images/Stock-Images/Alphabet/M.png') },
    { name: 'N', uri: require('../assets/images/Stock-Images/Alphabet/N.png') },
    { name: 'O', uri: require('../assets/images/Stock-Images/Alphabet/O.png') },
    { name: 'P', uri: require('../assets/images/Stock-Images/Alphabet/P.png') },
    { name: 'Q', uri: require('../assets/images/Stock-Images/Alphabet/Q.png') },
    { name: 'R', uri: require('../assets/images/Stock-Images/Alphabet/R.png') },
    { name: 'S', uri: require('../assets/images/Stock-Images/Alphabet/S.png') },
    { name: 'T', uri: require('../assets/images/Stock-Images/Alphabet/T.png') },
    { name: 'U', uri: require('../assets/images/Stock-Images/Alphabet/U.png') },
    { name: 'V', uri: require('../assets/images/Stock-Images/Alphabet/V.png') },
    { name: 'W', uri: require('../assets/images/Stock-Images/Alphabet/W.png') },
    { name: 'X', uri: require('../assets/images/Stock-Images/Alphabet/X.png') },
    { name: 'Y', uri: require('../assets/images/Stock-Images/Alphabet/Y.png') },
    { name: 'Z', uri: require('../assets/images/Stock-Images/Alphabet/Z.png') },
  ],
  // Animals (Land + Sea) - trimmed set of representative entries to keep file size manageable
  'Animals': [
    { name: 'Bee', uri: require('../assets/images/Stock-Images/Animals/Land Animals/bee.png') },
    { name: 'Bird', uri: require('../assets/images/Stock-Images/Animals/Land Animals/bird.png') },
    { name: 'Cat', uri: require('../assets/images/Stock-Images/Animals/Land Animals/cat.png') },
    { name: 'Dog', uri: require('../assets/images/Stock-Images/Animals/Land Animals/dog.png') },
    { name: 'Elephant', uri: require('../assets/images/Stock-Images/Animals/Land Animals/elephant.png') },
    { name: 'Lion', uri: require('../assets/images/Stock-Images/Animals/Land Animals/lion.png') },
    { name: 'Monkey', uri: require('../assets/images/Stock-Images/Animals/Land Animals/monkey.png') },
    { name: 'Pig', uri: require('../assets/images/Stock-Images/Animals/Land Animals/pig.png') },
    { name: 'Tiger', uri: require('../assets/images/Stock-Images/Animals/Land Animals/tiger.png') },
    { name: 'Whale', uri: require('../assets/images/Stock-Images/Animals/Sea Animals/1.png') },
    { name: 'Fish', uri: require('../assets/images/Stock-Images/Animals/Sea Animals/2.png') },
    { name: 'Crab', uri: require('../assets/images/Stock-Images/Animals/Sea Animals/4.png') },
    { name: 'Dolphin', uri: require('../assets/images/Stock-Images/Animals/Sea Animals/10.png') },
    { name: 'Turtle', uri: require('../assets/images/Stock-Images/Animals/Sea Animals/11.png') },
    { name: 'Shark', uri: require('../assets/images/Stock-Images/Animals/Sea Animals/13.png') },
  ],
  'Boxed Alphabet': [
    { name: 'Boxed A', uri: require('../assets/images/Stock-Images/Boxed Alphabet/A.png') },
    { name: 'Boxed B', uri: require('../assets/images/Stock-Images/Boxed Alphabet/B.png') },
    { name: 'Boxed C', uri: require('../assets/images/Stock-Images/Boxed Alphabet/C.png') },
    { name: 'Boxed D', uri: require('../assets/images/Stock-Images/Boxed Alphabet/D.png') },
  ],
  'Boxed Numbers 1-9': [
    { name: 'Boxed 1', uri: require('../assets/images/Stock-Images/Boxed Numbers 1-9/1.png') },
    { name: 'Boxed 2', uri: require('../assets/images/Stock-Images/Boxed Numbers 1-9/2.png') },
    { name: 'Boxed 3', uri: require('../assets/images/Stock-Images/Boxed Numbers 1-9/3.png') },
    { name: 'Boxed 4', uri: require('../assets/images/Stock-Images/Boxed Numbers 1-9/4.png') },
    { name: 'Boxed 5', uri: require('../assets/images/Stock-Images/Boxed Numbers 1-9/5.png') },
    { name: 'Boxed 6', uri: require('../assets/images/Stock-Images/Boxed Numbers 1-9/6.png') },
    { name: 'Boxed 7', uri: require('../assets/images/Stock-Images/Boxed Numbers 1-9/7.png') },
    { name: 'Boxed 8', uri: require('../assets/images/Stock-Images/Boxed Numbers 1-9/8.png') },
    { name: 'Boxed 9', uri: require('../assets/images/Stock-Images/Boxed Numbers 1-9/9.png') },
  ],
  // Keep representative subsets for remaining categories to avoid an extremely large file.
  // You can extend these lists as needed without changing calling code.
  'Comparing Quantities': [
    { name: '1 Apple', uri: require('../assets/images/Stock-Images/Comparing Quantities/1 apple.png') },
    { name: '2 Apples', uri: require('../assets/images/Stock-Images/Comparing Quantities/2 apples.png') },
    { name: '3 Apples', uri: require('../assets/images/Stock-Images/Comparing Quantities/3 apples.png') },
  ],
  Dates: [
    { name: 'Date 1', uri: require('../assets/images/Stock-Images/Dates/1.png') },
    { name: 'Date 10', uri: require('../assets/images/Stock-Images/Dates/10.png') },
  ],
  'Extra Objects': [
    { name: 'Balloon', uri: require('../assets/images/Stock-Images/Extra Objects/balloon.png') },
    { name: 'Chair', uri: require('../assets/images/Stock-Images/Extra Objects/Chair.png') },
    { name: 'Duck', uri: require('../assets/images/Stock-Images/Extra Objects/duck.png') },
  ],
  Fractions: [
    { name: 'Half Circle', uri: require('../assets/images/Stock-Images/Fractions/1_2 Circle.png') },
    { name: 'Quarter Circle', uri: require('../assets/images/Stock-Images/Fractions/1_4 Circle.png') },
  ],
  'Fruits and Vegetables': [
    { name: 'Apple', uri: require('../assets/images/Stock-Images/Fruits and Vegetables/Red Apple.png') },
    { name: 'Banana', uri: require('../assets/images/Stock-Images/Fruits and Vegetables/Saging.png') },
    { name: 'Carrot', uri: require('../assets/images/Stock-Images/Fruits and Vegetables/20.png') },
  ],
  'Length and Distance': [
    { name: 'Hand Span', uri: require('../assets/images/Stock-Images/Length and Distance/hand span.png') },
    { name: 'Tallest', uri: require('../assets/images/Stock-Images/Length and Distance/Tallest.png') },
  ],
  'Math Symbols': [
    { name: 'Plus', uri: require('../assets/images/Stock-Images/Math Symbols/plus.png') },
    { name: 'Minus', uri: require('../assets/images/Stock-Images/Math Symbols/minus.png') },
    { name: 'Equal', uri: require('../assets/images/Stock-Images/Math Symbols/equal.png') },
  ],
  Money: [
    { name: 'Piso', uri: require('../assets/images/Stock-Images/Money/28.png') },
    { name: 'Beynte', uri: require('../assets/images/Stock-Images/Money/32.png') },
    { name: 'Isandaan', uri: require('../assets/images/Stock-Images/Money/34.png') },
  ],
  Numbers: [
    { name: '1', uri: require('../assets/images/Stock-Images/Numbers/Numbers 1-100/1.png') },
    { name: '2', uri: require('../assets/images/Stock-Images/Numbers/Numbers 1-100/2.png') },
    { name: '3', uri: require('../assets/images/Stock-Images/Numbers/Numbers 1-100/3.png') },
    { name: '10', uri: require('../assets/images/Stock-Images/Numbers/Numbers 1-100/10.png') },
    { name: '100', uri: require('../assets/images/Stock-Images/Numbers/Numbers 1-100/100.png') },
  ],
  Patterns: [
    { name: '3 Shapes', uri: require('../assets/images/Stock-Images/Patterns/3 shapes.png') },
    { name: 'Up Down', uri: require('../assets/images/Stock-Images/Patterns/up down.png') },
  ],
  'School Supplies': [
    { name: 'Lapis', uri: require('../assets/images/Stock-Images/School Supplies/Lapis.png') },
    { name: 'Notebook', uri: require('../assets/images/Stock-Images/School Supplies/Notebook.png') },
    { name: 'Ruler', uri: require('../assets/images/Stock-Images/School Supplies/ruler.png') },
  ],
  Shapes: [
    { name: 'Circle', uri: require('../assets/images/Stock-Images/Shapes/circle.png') },
    { name: 'Square', uri: require('../assets/images/Stock-Images/Shapes/square.png') },
    { name: 'Triangle', uri: require('../assets/images/Stock-Images/Shapes/triangle.png') },
    { name: 'Rectangle', uri: require('../assets/images/Stock-Images/Shapes/rectangle.png') },
  ],
  'Time and Position': [
    { name: '12:00', uri: require('../assets/images/Stock-Images/Time and Position/12_00.png') },
    { name: '3:00', uri: require('../assets/images/Stock-Images/Time and Position/3_00.png') },
    { name: '6:00', uri: require('../assets/images/Stock-Images/Time and Position/6_00.png') },
    { name: '9:00', uri: require('../assets/images/Stock-Images/Time and Position/9_00.png') },
  ],
  Toys: [
    { name: 'Airplane', uri: require('../assets/images/Stock-Images/Toys/airplane.png') },
    { name: 'Ball', uri: require('../assets/images/Stock-Images/Toys/ball.png') },
    { name: 'Car', uri: require('../assets/images/Stock-Images/Toys/car.png') },
    { name: 'Robot', uri: require('../assets/images/Stock-Images/Toys/robot.png') },
  ],
};


